### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by lucas-janon**

### CODE REVIEW

**Comment by miparnisari** [comment]
Please rebase :)

**Comment by lucas-janon** [comment]
My bad, sorry.
Is it ok now?

**Comment by miparnisari** [comment]
This PR should only have this commit: https://github.com/miparnisari/arg.js/pull/19/commits/172a36475f0ea3f579052aafda9c3b264994b8d2

**Comment by lucas-janon** [comment]
It's ok to merge

**Pull request merged**
